### ISSUE TITLE
Using for ReactJS also

### ISSUE THREAD

**Issue by kennetpostigo** [nparashuram/maya-kai#1]
Read through your blog post and the youtube video and this seems really awesome! Really easy to setup and use. You mention in your post that `react-native` has an event system you plug into. Does that event system live in `react-native` or `react`? Would be awesome to do this on the web with `maya-kai` instead of using selenium.

**Comment by axemclion** [comment]
The event system does live in React and technically this should work on React (though I have not tried it out).

The events added and event plugins are specific to platform, but the EventPluginHub itself is in React. If you get a chance, please do try it on React and let me know how it goes :)
